config/routes.rb
Todaslistas::Application.routes.draw do
  

  config = Todaslistas::Application.config
  twitter = config.twitter_login.login_handler(:return_to => '/')
  mount twitter => 'login', :as => :twitter_login

  match 'logout' => 'sessions#logout', :as => :logout
  match 'about' => 'todo_lists#about', :as => :about

  resources :items do
    collection do
      put :sort
    end
  end

  resources :todo_lists do
    member do
      put :clear
    end
    collection do
      put :sort
    end
  end

  root :to => "todo_lists#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :todo_list

  validates_presence_of :description, :todo_list_id
  
  scope :done, :conditions => { :done => true }
  default_scope :order => 'done, position, created_at DESC'
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :items, :dependent => :destroy, :order => 'done, id DESC'

  validates_presence_of :name, :user_id 
  
  scope :latest, :order => 'position, created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todo_lists
  has_many :items, :through => :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Twitter::Login::Helpers

  def current_user
    @current_user ||= twitter_user && User.find_or_create_by_username(twitter_user.screen_name)
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    todo_list = current_user.todo_lists.find params[:todo_list_id]
    item = todo_list.items.create! params[:item]
    render item
  end

  def update
    item = current_user.items.find(params[:id], :readonly => false)
    # params will come in form of "item"=>{"<item id>"=>{"done"=>"1"}}
    item.update_attributes params[:item][params[:id]]
    render :json => item
  end

  def sort
    params[:item].each_with_index do |iid, i|
      Item.find(iid).update_attribute :position, i
    end
    render :json => true
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def logout
    twitter_logout
    redirect_to root_path
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

  def index
    if logged_in?
      @lists = current_user.todo_lists.latest.includes(:items)
      @todo_list = current_user.todo_lists.new
      @item = @todo_list.items.new
    else
      render :about
    end
  end

  def create
    @list = current_user.todo_lists.create! params[:todo_list]
    render :partial => 'todo_list', :locals => { :list => @list }
  end

  def destroy
    todo_list = current_user.todo_lists.find params[:id]
    todo_list.destroy
    
    render :json => todo_list
  end

  def clear # clear done items
    todo_list = current_user.todo_lists.find params[:id]
    done_items = todo_list.items.done.destroy_all
    
    render :json => done_items
  end

  def sort
    params[:todo_list].each_with_index do |lid, i|
      TodoList.find(lid).update_attribute :position, i
    end
    render :json => true
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def mac?
    request.user_agent =~ /\bMac OS\b/
  end
  
  def analytics_code
    <<-CODE
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
    var pageTracker = _gat._getTracker("UA-5355510-2");
    pageTracker._trackPageview();
    } catch(err) {}
    CODE
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/items/_item.html.erb
<%= content_tag_for :li, item, :class => item.done? ? 'done' : nil do %>
  <%= form_for item, :index => item.id, :remote => true do |i| %>
    <div>
      <% value = capture do %>
        <%= i.check_box :done %>
        <span><%= item.description %></span>
      <% end %>
      <%= i.label :done, value %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="author" lang="hr" content="Ivana Vasilj, ivasilj@gmail.com" />
    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    
    <title>Todas Listas</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <link rel="icon" type="image/png" href="/favicon.ico" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

    <meta name="description" content="Todas Listas - view all your todos at once. A simple and free to-do list web-app, lists all your grouped tasks on a same page." />

    <meta name="google-site-verification" content="MsnXE0MdO1751wU2U6RCk5kHmoIwaVHuUmBZK3twzmE" />
    
    <!--[if lt IE 9]>
    <script type="text/javascript">
    (function(){var e = "abbr,article,aside,audio,bb,canvas,datagrid,datalist,details,dialog,eventsource,figure,footer,header,hgroup,mark,menu,meter,nav,output,progress,section,time,video".split(',');for(var i=0;i<e.length;i++){document.createElement(e[i])}})()
    </script>
    <![endif]-->
  </head>

  <body>
    <header>
      <h1><a href="/about"><img src="/assets/logo.png" alt="Todas Listas" /></a></h1>

    <% if logged_in? %>
      <nav>
        <ol>
          <li><a href="/about">About</a></li>
          <li><a href="/logout">Sign out <strong>@<%= current_user.username %></strong></a></li>
        </ol>
      </nav>
    <% end %>
    </header>
    
    <% unless logged_in? %>
      <%= link_to 'Sign in with Twitter', twitter_login_path, :class => 'main' %>
    <% end %>

    <%= yield %>

    <%= javascript_tag analytics_code if Rails.env.production? %>
      
  </body>
</html>

app/views/todo_lists/_todo_list.html.erb
<%= content_tag_for :li, list, :class => list.items.any?(&:done?) ? 'has-done' : nil do %>
  <h2><%= list.name %></h2>

  <ol class="actions">
    <li><a class="new" href="#new" title="New item">+</a></li>
    <li><%= link_to mac?? '✗' : 'x', list, :remote => true, :method => 'delete', :class => 'delete',
      :title => 'Delete list', :confirm => 'Are you sure you want to delete this whole list?' %></li>
    <li><%= link_to mac?? '✓' : ':)', clear_todo_list_path(list), :remote => true, :method => 'put', :class => 'clear',
      :title => 'Clear done items' %></li>
  </ol>

  <ul class="items">
    <%= render :partial => 'items/item', :collection => list.items %>
  </ul>
<% end %>

app/views/todo_lists/about.html.erb
<% if logged_in? %>
  <a href="/" class="main"><%= mac?? '←' : '<' %> Back to My Lists</a>
<% end %>

<ol id="about">

  <li>
    <h2>About the app</h2>
    <p>I made this little app to serve my to-do needs. It's built with:</p>
    <ul>
      <li>Ruby, Rails 3.1</li>
      <li>jQuery, jQuery UI, CoffeeScript</li>
      <li>HTML5, CSS3</li>
    </ul>
  </li>

  <li>
    <h2>Yet another to-do list?</h2>
    <ul>
      <li>All your tasks in one place.</li>
      <li>Simple, yet organized.</li>
      <li>Web app. Looks great on your mobile device.</li>
      <li>Free &amp; <a href="https://github.com/ivana/todofrenzy">opensource</a>.</li>
    </ul>
  </li>

  <li class="vcard">
    <h2>Like it?</h2>
    <p>
      My name is <span class="fn n"><span class="given-name">Ivana</span> <span class="family-name">Vasilj</span></span>.
      Find me on:
    </p>
    <ul>
      <li>twitter as <a rel="me" class="url" href="http://twitter.com/ivanavasilj">@ivanavasilj</a></li>
      <li><a rel="me" class="url" href="http://ivana.im/">ivana.im</a> &ndash; my home site and blog</li>
    </ul>
    <p>Drop me a line if you find Todas Listas useful!</p>
  </li>

</ol>

app/views/todo_lists/index.html.erb
<a href="#newlist" class="create main">New List</a>

<%= form_for @todo_list, :remote => true, :format => :html do |l| %>
  <div>
    <%= l.label(:name, 'List title:') %>
    <%= l.text_field(:name) %>
    <%= l.submit('Create') %>
    <input type="button" value="Cancel" />
  </div>
<% end %>

<%= form_for @item, :remote => true, :format => :html do |i| %>
  <div>
    <%= i.label :description, 'New item:' %>
    <%= i.text_field :description, :size => 24 %>

    <%= hidden_field_tag :todo_list_id %>
  </div>

  <div>
    <%= i.submit 'Add new item' %>
    <input type="button" value="Close" />
  </div>
<% end %>

<ol id="todas">
  <%= render :partial => @lists, :as => :list %>
</ol>

<% if @lists.count > 1 %><p>Use drag &amp; drop to sort lists and tasks!</p><% end %>

<footer>
  <h1>keyboard shortcuts:</h1>
  <dl>
    <dt>Shift + A</dt><dd>new list</dd>
    <dt>ESC</dt><dd>cancel form</dd>
  </dl>
</footer>